CorporateRewards/docs-myrewards

source/index.html.md

Also, update the list transactions to remove the instruction to use it
for finding the user's balance; instead prefer to use the last
transaction endpoint.

Add docs for showing the user's last transaction

---

source/index.html.md

Including:
- Listing transactions
- Showing the last transaction

Add id to transactions

---

source/index.html.md

update docs with endpoint for DataFields scoped to Promotion

---

source/index.html.md

Docs for PerformanceProducts#create on V2

---

source/index.html.md

Enhancement #5048 Api Performance Products Update Docs

---

.github/ISSUE_TEMPLATE.md
README.md
source/includes/api/core/_site_messages.md

confusing if they were in the same table.

Separate URL and Body params into two tables as they were potentially

---

source/index.html.md

Corrected case for token header example

---

.circleci/config.yml

Updating image

---

source/includes/api/core/_registration_questions.md
source/includes/api/core/_transactions.md
source/includes/api/core/_user_groups.md
source/includes/api/core/_users.md

Spelling and grammar corrections

---

source/includes/api/core/_user_groups.md

add docs for creating a user_group

---

source/includes/sso/_index.md
source/index.html.md

Connects CorporateRewards/MyRewards#5985

adding SSO documentation

---

source/includes/api/core/_user_groups.md
source/includes/api/core/_user_groups_permissions.md
source/includes/api/core/_users_permissions.md

Connects CorporateRewards/MyRewards#5888

minor changes required

---

source/includes/sso/_index.md

formatting SAML form example

---

source/includes/api/extra_features/_target_trackers.md
source/index.html.md

Connects CorporateRewards/MyRewards#6268

added docs for target tracker index

---

source/includes/api/extra_features/_target_trackers.md

added docs for user target tracker endpoint

---

source/includes/api/core/_transactions.md

connects corporaterewards/myrewards#5476

removed programme budget reference

---

source/includes/api/extra_features/_target_trackers.md
source/includes/sso/_index.md
source/index.html.md
source/layouts/layout.erb

removed log and fixed types and typos

---

source/index.html.md

removed reference to faqs

---

source/includes/api/performance/_data_fields.md

remove email

---

source/includes/api/performance/_allocated_claims.md

connects CorporateRewards/myrewards#6902

updates json blob

---

source/includes/api/core/_transactions.md

* corrects `Person2Person transfer` (prev. `Person 2 Person Transfer`)

Correction to transaction type

---

source/includes/sso/_index.md

* updates `AudienceRestriction` to required format
* refactors timestamps to epoch for examples (happy 50th birthday unix epoch)
* resolves #57

Updated SSO docs

---

source/includes/api/core/_registration_questions_list_of_values.md
source/index.html.md

connects CorporateRewards/MyRewards#7351

add registration questions list of values endpoint

---

source/includes/api/core/_registration_questions_list_of_values.md

connects CorporateRewards/myrewards#7352

add registration questions list of values post endpoint

---

source/includes/api/performance/_self_claims.md
source/index.html.md

connects CorporateRewards/MyRewards#7650

add get self claims docs

---

source/includes/api/performance/_self_claims.md

connects CorporateRewards/MyRewards#7653

add self claim decline docs

---

source/includes/api/performance/_self_claims.md

connects CorporateRewards/MyRewards#7654

add self claim approve docs

---

source/includes/api/core/_users.md

show how to send over multiple answers to a registration question

---

source/includes/api/core/_user_groups.md

- correction for manage user groups endpoint reference

Manage User Groups inconsistency

---

source/includes/api/reward/_points_overrides.md
source/index.html.md

Connects CorporateRewards/MyRewards#7578

Add points override docs

---

.gitignore
source/includes/api/core/_user_groups.md

changes requested as per ABeadle

---

source/includes/api/core/_users.md

show how to unset company

---

source/includes/api/core/_companies.md
source/index.html.md

connects CorporateRewards/myrewards#7763

add companies api docs

---

source/includes/api/core/_companies.md

connects CorporateRewards/myrewards#7764
connects CorporateRewards/myrewards#7765

add documentation for create and update company endpoints

---

source/includes/api/core/_companies.md

connects CorporateRewards/myrewards#7975

add delete company docs

---

source/includes/sso/_index.md

updating for configurable attribute name in SSO

---

source/includes/api/recognition/_submissions.md
source/index.html.md

Connects https://github.com/CorporateRewards/myrewards/issues/8065

Feature/#8065 Get campaign submissions endpoint 

---

source/includes/api/recognition/_submissions.md

Connects https://github.com/CorporateRewards/myrewards/issues/8068

Added documentation for decline submission endpoint

---

source/includes/api/core/_user_groups.md

Connects CorporateRewards/myrewards#8118

Add documentation for GET user group api request

---

source/includes/api/core/_user_groups.md

Add delete user group documentation

---

source/includes/api/core/_user_groups.md

Connects [8315](https://github.com/CorporateRewards/myrewards/issues/8315)

Feature/#8315 Update user group endpoint

---

source/includes/api/core/_transactions.md

Connects [8330](https://github.com/CorporateRewards/myrewards/issues/8330)

Bug/#8330 Creating Transactions via API

---

source/includes/api/performance/_sales_data.md

Connects [8426](https://github.com/CorporateRewards/myrewards/issues/8426)

Bug/#8426 Update sales data response

---

source/includes/api/core/_user_groups.md

Links https://github.com/CorporateRewards/myrewards/issues/8477

Add user_group description column to API docs

---

source/includes/api/recognition/_recognition_wall.md
source/index.html.md

connects CorporateRewards/myrewards#8455

add recognition wall endpoint docs

---

source/includes/api/performance/_reward_points.md

Connects CorporateRewards/myrewards#8623

Add reward point create endpoint docs

---

source/includes/api/core/_transactions.md

connects CorporateRewards/myrewards#8758

remove order adjustment and cancellation from create a transaction docs

---

source/includes/api/core/_users_badges.md

Connects [#8795](https://github.com/CorporateRewards/myrewards/issues/8795)

Get and update badges endpoints

---

Dockerfile

Should hopefully fix CircleCI build

Rework: Technical/update from slate upstream jul 23

---

source/includes/api/core/_users.md
source/includes/sso/_saml.md

add warning messaging about JIT user provisioning
